spring:
  config:
    activate:
      on-profile: prod
    profiles:
      include: secret
  data:
    redis:
      host: redis_1
      port: ${REDIS_PORT}
      password: "${REDIS_PW}"
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

  datasource:
    url: jdbc:mysql://mysql_1:3306/${DB_NAME}
    username: teama5
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate # Flyway가 스키마 관리
    properties:
      hibernate:
        format_sql: false
        highlight_sql: false
        use_sql_comments: false
    show-sql: false
  flyway:
    enabled: true
    baseline-on-migrate: true # 기존 DB에 적용 시 필요
    locations: classpath:db/migration

logging:
  level:
    com.back: INFO
    org.hibernate.SQL: WARN
    org.hibernate.orm.jdbc.bind: WARN
    org.hibernate.orm.jdbc.extract: WARN
    org.springframework.transaction.interceptor: WARN

custom:
  base-url: http://localhost:8080 #프로필 이미지 등 서버 접근용 BASE URL

  site:
    domain: "${custom.prod.domain}"
    backUrl: "${custom.prod.backUrl}"
    frontUrl: "${custom.prod.frontUrl}"

  jwt:
    secretPattern: ${JWT_SECRET}
    accessExpireSeconds: 3600
    refreshExpireSeconds: 604800

  cookie:
    secure: true
    sameSite: "None"
    path: /

cloud:
  aws:
    s3:
      bucket: matchduo-profile
    region:
      static: ap-northeast-2
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    stack:
      auto: false