spring:
  datasource:
    url: jdbc:mysql://mysql_1:3306/${DB_NAME}
    username: ${EC2_DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
        highlight_sql: false
        use_sql_comments: false
    show-sql: false

logging:
  level:
    com.back: INFO
    org.hibernate.SQL: WARN
    org.hibernate.orm.jdbc.bind: WARN
    org.hibernate.orm.jdbc.extract: WARN
    org.springframework.transaction.interceptor: WARN

custom:
  site:
    domain: "${custom.prod.domain}"
    backUrl: "${custom.prod.backUrl}"
    frontUrl: "${custom.prod.frontUrl}"

  jwt:
    secretPattern: ${JWT_SECRET}
    accessExpireSeconds: 1800
    refreshExpireSeconds: 1209600

  cookie:
    secure: true
    sameSite: Lax
    path: /